var = input('Digite algo: ')
print('O tipo primitivo de {} é {}'.format(var, type(var)))
print('Só tem espaço: {}'.format(var.isspace()))
print('É numérico: {}'.format(var.isnumeric()))
print('É alfabético: {}'.format(var.isalpha()))
print('É alfanumérico: {}'.format(var.isalnum()))
print('Está em maiúsculo: {}'.format(var.isupper()))
print('Está em minúsculo: {}'.format(var.islower()))
print('Está capitalizada: {}'.format(var.istitle()))
